#pragma once

#include <xmmintrin.h>
#include <memory>
#include <map>
#include <typeindex>
#include <list>
#include <algorithm>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <string>
#include <thread>
#include <mutex>
#include <sstream>
#include <string>
#include <cmath>
#include <cstdlib>
#include <cstdint>
#include <cassert>
#include <vector>
#include <unordered_map>
#include <initializer_list>